"""
MongoDB Query Demonstrations
============================
Runnable PyMongo examples for the Online Shopping Management System.

Run:
    python sample_queries.py

Prerequisites:
    - MongoDB running locally on mongodb://localhost:27017/
    - The sample data generated by shopping_system.py
"""

import os
from datetime import datetime
from bson import ObjectId
from pymongo import MongoClient, DESCENDING, ASCENDING
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
DB_NAME = os.getenv("DB_NAME", "online_shopping_db")

client = MongoClient(MONGO_URI)
db = client[DB_NAME]


def print_section(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def first_customer():
    return db.customers.find_one()


def first_product():
    return db.products.find_one()


# ============================================================================
# BASIC CRUD QUERIES
# ============================================================================

def basic_crud_queries():
    print_section("1. BASIC CRUD QUERIES")

    customer = first_customer()
    product = first_product()

    if not customer or not product:
        print("No sample data found. Run: python shopping_system.py")
        return

    # READ: Find customer by email
    print("\nCustomer by email:")
    result = db.customers.find_one({"email": customer["email"]})
    print(result)

    # READ: Find active customers
    print("\nActive customers:")
    for item in db.customers.find({"isActive": True}).limit(10):
        print(f"- {item.get('firstName', '')} {item.get('lastName', '')} | {item.get('email', '')}")

    # UPDATE: Customer preference
    db.customers.update_one(
        {"_id": customer["_id"]},
        {"$set": {"preferences.currency": "USD"}}
    )
    print("\nUpdated customer currency preference.")

    # UPDATE: Add an address only if one is not already present.
    if not any(a.get("addressId") == "demo_work_address" for a in customer.get("addresses", [])):
        db.customers.update_one(
            {"_id": customer["_id"]},
            {"$push": {"addresses": {
                "addressId": "demo_work_address",
                "type": "work",
                "street": "100 Business Ave",
                "city": "New York",
                "state": "NY",
                "zipCode": "10002",
                "country": "USA",
                "isDefault": False
            }}}
        )
        print("Added a demonstration work address.")

    # READ: Find product by SKU
    print("\nProduct by SKU:")
    print(db.products.find_one({"sku": product["sku"]}))

    # READ: Text search
    print("\nText search for 'wireless headphones':")
    for item in db.products.find({"$text": {"$search": "wireless headphones"}}):
        print(f"- {item['name']} | ${item['price']}")

    # READ: Price range
    print("\nProducts between $50 and $200:")
    for item in db.products.find({
        "price": {"$gte": 50, "$lte": 200},
        "isActive": True
    }).sort("price", ASCENDING):
        print(f"- {item['name']} | ${item['price']}")

    # UPDATE: Stock safely for demonstration, then restore it.
    original_stock = product["stock"]
    db.products.update_one(
        {"_id": product["_id"]},
        {"$inc": {"stock": -1}}
    )
    print(f"\nStock temporarily decreased: {original_stock} -> {original_stock - 1}")
    db.products.update_one(
        {"_id": product["_id"]},
        {"$inc": {"stock": 1}}
    )
    print("Stock restored after demonstration.")

    # READ: Orders for a customer
    print("\nOrders for first customer:")
    for order in db.orders.find(
        {"customerId": customer["_id"]}
    ).sort("orderDate", DESCENDING):
        print(f"- {order['orderNumber']} | {order['status']} | ${order['grandTotal']}")

    # READ: Pending orders
    print("\nPending orders:")
    for order in db.orders.find({"status": "pending"}):
        print(f"- {order['orderNumber']}")

    # UPDATE: Demonstrate order status and restore it.
    order = db.orders.find_one({"customerId": customer["_id"]})
    if order:
        old_status = order["status"]
        db.orders.update_one(
            {"_id": order["_id"]},
            {"$set": {"status": "shipped", "trackingNumber": "DEMO-TRK-123"}}
        )
        print(f"\nOrder {order['orderNumber']} status: {old_status} -> shipped")

        db.orders.update_one(
            {"_id": order["_id"]},
            {"$set": {"status": old_status}}
        )
        print(f"Order status restored to: {old_status}")


# ============================================================================
# ADVANCED AGGREGATIONS
# ============================================================================

def customer_order_history():
    customer = first_customer()
    if not customer:
        return []

    return list(db.customers.aggregate([
        {"$match": {"_id": customer["_id"]}},
        {
            "$lookup": {
                "from": "orders",
                "localField": "_id",
                "foreignField": "customerId",
                "as": "orders"
            }
        },
        {
            "$project": {
                "name": {"$concat": ["$firstName", " ", "$lastName"]},
                "email": 1,
                "totalOrders": {"$size": "$orders"},
                "totalSpent": {"$sum": "$orders.grandTotal"},
                "avgOrderValue": {"$avg": "$orders.grandTotal"}
            }
        }
    ]))


def product_performance():
    return list(db.orders.aggregate([
        {"$match": {"status": {"$nin": ["cancelled"]}}},
        {"$unwind": "$items"},
        {
            "$group": {
                "_id": "$items.productId",
                "productName": {"$first": "$items.name"},
                "sku": {"$first": "$items.sku"},
                "totalQuantitySold": {"$sum": "$items.quantity"},
                "totalRevenue": {"$sum": "$items.totalPrice"},
                "avgSellingPrice": {"$avg": "$items.unitPrice"},
                "orderCount": {"$sum": 1}
            }
        },
        {"$sort": {"totalRevenue": -1}},
        {"$limit": 10}
    ]))


def monthly_sales():
    return list(db.orders.aggregate([
        {"$match": {"status": {"$nin": ["cancelled"]}}},
        {
            "$group": {
                "_id": {
                    "year": {"$year": "$orderDate"},
                    "month": {"$month": "$orderDate"}
                },
                "totalOrders": {"$sum": 1},
                "totalRevenue": {"$sum": "$grandTotal"},
                "avgOrderValue": {"$avg": "$grandTotal"},
                "totalItems": {"$sum": {"$size": "$items"}},
                "totalDiscount": {"$sum": "$discountTotal"}
            }
        },
        {"$sort": {"_id.year": -1, "_id.month": -1}}
    ]))


def revenue_by_category():
    return list(db.orders.aggregate([
        {"$match": {"status": {"$nin": ["cancelled"]}}},
        {"$unwind": "$items"},
        {
            "$lookup": {
                "from": "products",
                "localField": "items.productId",
                "foreignField": "_id",
                "as": "product"
            }
        },
        {"$unwind": "$product"},
        {
            "$group": {
                "_id": "$product.category",
                "totalRevenue": {"$sum": "$items.totalPrice"},
                "totalItemsSold": {"$sum": "$items.quantity"},
                "uniqueProducts": {"$addToSet": "$items.productId"}
            }
        },
        {
            "$project": {
                "_id": 0,
                "category": "$_id",
                "totalRevenue": 1,
                "totalItemsSold": 1,
                "uniqueProductCount": {"$size": "$uniqueProducts"}
            }
        },
        {"$sort": {"totalRevenue": -1}}
    ]))


def customer_segmentation():
    return list(db.orders.aggregate([
        {"$match": {"status": {"$nin": ["cancelled"]}}},
        {
            "$group": {
                "_id": "$customerId",
                "lastOrderDate": {"$max": "$orderDate"},
                "orderCount": {"$sum": 1},
                "totalSpent": {"$sum": "$grandTotal"}
            }
        },
        {
            "$lookup": {
                "from": "customers",
                "localField": "_id",
                "foreignField": "_id",
                "as": "customer"
            }
        },
        {"$unwind": "$customer"},
        {
            "$project": {
                "customerName": {
                    "$concat": ["$customer.firstName", " ", "$customer.lastName"]
                },
                "email": "$customer.email",
                "lastOrderDate": 1,
                "orderCount": 1,
                "totalSpent": 1,
                "avgOrderValue": {"$divide": ["$totalSpent", "$orderCount"]},
                "daysSinceLastOrder": {
                    "$floor": {
                        "$divide": [
                            {"$subtract": [datetime.utcnow(), "$lastOrderDate"]},
                            1000 * 60 * 60 * 24
                        ]
                    }
                }
            }
        },
        {
            "$addFields": {
                "segment": {
                    "$switch": {
                        "branches": [
                            {
                                "case": {
                                    "$and": [
                                        {"$lte": ["$daysSinceLastOrder", 30]},
                                        {"$gte": ["$totalSpent", 500]}
                                    ]
                                },
                                "then": "VIP"
                            },
                            {
                                "case": {
                                    "$and": [
                                        {"$lte": ["$daysSinceLastOrder", 60]},
                                        {"$gte": ["$orderCount", 3]}
                                    ]
                                },
                                "then": "Loyal"
                            },
                            {
                                "case": {"$lte": ["$daysSinceLastOrder", 30]},
                                "then": "Active"
                            },
                            {
                                "case": {"$lte": ["$daysSinceLastOrder", 90]},
                                "then": "At Risk"
                            }
                        ],
                        "default": "Inactive"
                    }
                }
            }
        },
        {"$sort": {"totalSpent": -1}}
    ]))


def product_review_analysis():
    return list(db.reviews.aggregate([
        {
            "$group": {
                "_id": "$productId",
                "avgRating": {"$avg": "$rating"},
                "totalReviews": {"$sum": 1},
                "verifiedReviews": {
                    "$sum": {
                        "$cond": [{"$eq": ["$verifiedPurchase", True]}, 1, 0]
                    }
                }
            }
        },
        {
            "$lookup": {
                "from": "products",
                "localField": "_id",
                "foreignField": "_id",
                "as": "product"
            }
        },
        {"$unwind": "$product"},
        {
            "$project": {
                "_id": 0,
                "productName": "$product.name",
                "sku": "$product.sku",
                "avgRating": {"$round": ["$avgRating", 1]},
                "totalReviews": 1,
                "verifiedPercentage": {
                    "$round": [
                        {
                            "$multiply": [
                                {"$divide": ["$verifiedReviews", "$totalReviews"]},
                                100
                            ]
                        },
                        1
                    ]
                }
            }
        },
        {"$sort": {"avgRating": -1}}
    ]))


def cart_abandonment():
    return list(db.carts.aggregate([
        {"$match": {"items.0": {"$exists": True}}},
        {
            "$lookup": {
                "from": "customers",
                "localField": "customerId",
                "foreignField": "_id",
                "as": "customer"
            }
        },
        {"$unwind": "$customer"},
        {
            "$project": {
                "_id": 0,
                "customerName": {
                    "$concat": ["$customer.firstName", " ", "$customer.lastName"]
                },
                "email": "$customer.email",
                "itemCount": {"$size": "$items"},
                "subtotal": 1,
                "daysInactive": {
                    "$floor": {
                        "$divide": [
                            {"$subtract": [datetime.utcnow(), "$lastUpdated"]},
                            1000 * 60 * 60 * 24
                        ]
                    }
                }
            }
        },
        {"$match": {"daysInactive": {"$gte": 3}}},
        {"$sort": {"subtotal": -1}}
    ]))


def inventory_alerts():
    return list(db.products.aggregate([
        {"$match": {"stock": {"$lte": 20}, "isActive": True}},
        {
            "$project": {
                "_id": 0,
                "name": 1,
                "sku": 1,
                "stock": 1,
                "category": 1,
                "urgency": {
                    "$switch": {
                        "branches": [
                            {"case": {"$eq": ["$stock", 0]}, "then": "OUT_OF_STOCK"},
                            {"case": {"$lte": ["$stock", 5]}, "then": "CRITICAL"},
                            {"case": {"$lte": ["$stock", 10]}, "then": "LOW"}
                        ],
                        "default": "MODERATE"
                    }
                }
            }
        },
        {"$sort": {"stock": 1}}
    ]))


def payment_success_rate():
    return list(db.payments.aggregate([
        {
            "$group": {
                "_id": "$method",
                "totalTransactions": {"$sum": 1},
                "successful": {
                    "$sum": {
                        "$cond": [{"$eq": ["$status", "completed"]}, 1, 0]
                    }
                },
                "failed": {
                    "$sum": {
                        "$cond": [{"$eq": ["$status", "failed"]}, 1, 0]
                    }
                },
                "totalAmount": {"$sum": "$amount"},
                "avgAmount": {"$avg": "$amount"}
            }
        },
        {
            "$project": {
                "_id": 0,
                "paymentMethod": "$_id",
                "totalTransactions": 1,
                "successRate": {
                    "$round": [
                        {
                            "$multiply": [
                                {"$divide": ["$successful", "$totalTransactions"]},
                                100
                            ]
                        },
                        2
                    ]
                },
                "totalAmount": 1,
                "avgAmount": {"$round": ["$avgAmount", 2]}
            }
        }
    ]))


def hourly_order_pattern():
    return list(db.orders.aggregate([
        {"$match": {"status": {"$nin": ["cancelled"]}}},
        {
            "$group": {
                "_id": {"$hour": "$orderDate"},
                "orderCount": {"$sum": 1},
                "revenue": {"$sum": "$grandTotal"}
            }
        },
        {"$sort": {"_id": 1}}
    ]))


def show_aggregations():
    print_section("2. ADVANCED AGGREGATIONS")

    reports = [
        ("Customer Order History", customer_order_history),
        ("Product Performance", product_performance),
        ("Monthly Sales", monthly_sales),
        ("Revenue by Category", revenue_by_category),
        ("Customer Segmentation", customer_segmentation),
        ("Product Review Analysis", product_review_analysis),
        ("Cart Abandonment", cart_abandonment),
        ("Inventory Alerts", inventory_alerts),
        ("Payment Success Rate", payment_success_rate),
        ("Hourly Order Pattern", hourly_order_pattern),
    ]

    for title, function in reports:
        print(f"\n--- {title} ---")
        try:
            results = function()
            if not results:
                print("No matching data.")
            else:
                for result in results[:10]:
                    print(result)
        except Exception as exc:
            print(f"Skipped: {exc}")


# ============================================================================
# OPTIONAL FEATURES
# ============================================================================

def transaction_example():
    """
    Transactions require MongoDB running as a replica set or sharded cluster.
    This function is intentionally not executed by default.
    """
    print_section("OPTIONAL: TRANSACTION EXAMPLE")
    print("Transactions require a MongoDB replica set/sharded cluster.")
    print("The main shopping_system.py contains the application-level order flow.")


def change_stream_example():
    """
    Change streams require MongoDB running as a replica set or sharded cluster.
    This function is intentionally not executed by default.
    """
    print_section("OPTIONAL: CHANGE STREAM EXAMPLE")
    print("Change streams require a MongoDB replica set/sharded cluster.")
    print("Enable this feature only when running MongoDB in that configuration.")


if __name__ == "__main__":
    try:
        basic_crud_queries()
        show_aggregations()
    finally:
        client.close()
